# Generated by Django 4.0.6 on 2022-08-03 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_user_is_online'),
        ('common', '0003_user_avatar'),
    ]

    operations = [
    ]
